### PR TITLE
Is not building at Vercel, a lot of errors related to typescript and no passing lang as params.

### PR DESCRIPTION
**Pull request by julioflima**
I've forked and made my own project using yours, so I've needed pages after the `"/[lang]"...`

So, review my PR, please. If causes any structural problems, I could resolve them.

Follow in below the link proving that, now it is working!

## DEMO:
[https://i18n-typescript-app.vercel.app/](https://i18n-typescript-app.vercel.app/)

### CODE REVIEW

**Comment by BiscuiTech** [comment]
Hey thanks for taking the time to make a PR. I'll review this asap.

**Comment by BiscuiTech** [comment]
Hey! There's some good changes here. I updated this tutorial to reflect some changes since the last version of Nextjs, so could you please rebase your changes on the latest master? Thanks.

**Comment by julioflima** [comment]
Seams like you removed all that I made and made it right, without `any`.

Good job. 

I just, gonna build and see if will deploy to close the PR.

**Comment by julioflima** [comment]
I think that could be more generic if the arrays `['en', 'fr']` were extracted do locales array, from directory translations.

If you accept the PR, I'll send another fixing this.

**Comment by julioflima** [comment]
It is deployed, as the bot confirmed.

**Comment by BiscuiTech** [comment]
I'm seeing some inconsistencies with the web pages. Can you rebase (or merge master into yours) your PR on the latest branch? 
I fixed a merge conflict that you pushed into the PR, as well as removed an `any`. The rest looks good.

**Comment by julioflima** [comment]
Didn't work the merge, but I'm seeing what you are talking about. I'll gonna solve it.

**Comment by julioflima** [comment]
If I don't put the `any` at `useLocalStorage` this happens:

image

In consequence, will not build at Vercel. My objective here is to leave this tutorial so good that can be deployed at Vercel when de dev clicks in deploy and not breaking. Because if the dev has to understand the whole code, and fixes to use, he gonna give up the idea of using this.

image


I've spent a day fixing to use this.

I agree that `any` is not ideal, but gonna solve it, and if you don't have any other solution I'll be happy if you accept.

**Comment by julioflima** [comment]
I'd like to explain this part of the code, to not have any misunderstanding anymore. 

This is a lot of verbose but this adds the lang at the params structure to adds in the other routes the lang. I spent most of my time doing this part of the code to make work, and I believe is the Cerne of this PR.
  

```javascript
const paths = locales.reduce(
    (acc: IUserPaths[], idiom: Locale) => [
      ...acc,
      ...sampleUserData.map((user) => ({
        params: { id: user.id.toString(), lang: idiom },
      })),
    ],
    []
  );

```

**Comment by BiscuiTech** [comment]
I'm gonna have to disagree here. I understand you want to eliminate errors from Vercel, but adding an `any` is counter-productive to TS. 
I now realized that this repo had `any` in it. Sorry if this gave you the wrong idea. I fixed it.

I pushed a recent update fixing most of the issues. If you could merge those updates on your side one last time, that'd be appreciated. Thanks!

**Comment by julioflima** [comment]
And `unknown` is productive? Ok then.

**Comment by julioflima** [comment]
Nice about flatMap. I was wondering about something like this, in these days, I didn't know that exists. 

But seems like is not compatible with me. Maybe is a problem with my node version.
image

In the Vercel is building great.
https://i18n-typescript-app.vercel.app/en

**Comment by BiscuiTech** [comment]
> And `unknown` is productive? Ok then.

'any' actually disables typescript type checking. 'unknown' says to typescript that the type is unknown until it runs. 

If you're unfamiliar with the differences, I'd recommend diving into the TS docs.

As for the flatMap, I believe it was a 2019 ECMA addition. You may need to update your node, or make sure to install the current packages from npm.

**Comment by BiscuiTech** [comment]
Thanks for the update :)
Merging this.

**Comment by julioflima** [comment]
Thanks for the explanation about any, is really valid, I've checked.

**Pull request merged**
